language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
  sauce_connect: true
env:
  global:
  - secure: RGgCDkp99/x+GV8sYQFTnRgEh9NWgKqYJTGpZMW9HcjcCBqGVVtFSYGwg9Lei70R6zUoIPOWhLqdRBuZBL4c3FR05YKOmnUQOFNTu0+RsDm5EKHlkaDQvAfdu4S+BdQthJp+RPoDddryEzOZ/epiQXVkGuqCb9k/3dhiapG9CyIc3ziZdgxmyQ2rurkNPxT+0MzOfLs2G4rV18xIu06LA6HSyO6MYhCb5lKpd4QtGtP/84/ENbuWCzXokzvVq9xYdYNmjJFK6ZuIk+5CQWmUKQFGS3z7Fpa3ye/olnpHshXhiWuLzt5cMHeWPKvcGz5+PUoEFD4Ucb+8TnR8SyaTNPNuuXyzWgSZPdMLPO7HCiYST2NivwGu45yA8ndo58C46MfZowCar+8iY9atQsB9HUEsKEjigWBre3wll3lQEgs9ogOeYYZgBVeFdY19BxTXc2lW/Qci/GJbM+9DJqAAAmdjmsTNWbah5kojfKmjTfKKUMtQ8RNDj6mbgqEjIxZ3iyolc8mEO2O9BL46eiWlqB3hZdX5lcGHFvlCiJX5AQx9f8zf02jauF56i0UaVsRrz9AYG6iNlbmaIi6/jo9t/xAa8CWn4OCJhWxK/LJsqgBL3U02MQd5A+MZgSnI0vTElMrkszulzJJyV2Ub8djAfVtjdQ35UGZbf09EhchWphg=
  - secure: l76FkemNYB3+7U6oZdLk3eCdeAkBg4VsLSxoh2sGzzD8RoVkMcqxFcjJMc1COOJxnj1MlT4rmtqQL3vNZbSO0rlNagToXxu2p6WiMLfkvdJs6Hdr0eLKdboCOJTEJ9LglJcUw6QAbmk6HXY/ny/rLGt4YwAzx5JwLRTpeqTKax2Z2u/9d7EAEy1+b9YrdSME78bSnlsX6ju8G1qkYDmCzbBAOiHErHnL14MEyd9TG4PCRLVkKSG25skSb2TewVF0k+0eGKnCpNVAydxxRJZ6xWfh4VpRFww7elvc1MdZc82qmvK/vvpw9+9maYMs5nDZPU9i60DQKaI/vUl8TFC4QIbMDfyRa5gilJspt5PGvm4anjxTYuuVS8bKSJxcw9Xg05Jx/cOY6swQycX/bP4mQNyAd5E0lgI2QaxS/d9fG5CiiW+FMbjq91kHKaXJi60qsb/IeMktIVNpIGp6t1+UfolIvUeMqAXxJcIG8ZcCXHdVHO1CX6VdJ3dQkLCG4outmWy9YT2KHzdvRyU0VwL93GcK1MTw7Xvw8xNt7QFBFJxtZdzUuUsw3f4V0Ph551y5KMrw+01bTRfEf13Nqg9M6CnMQh8VZkoimWbmnyCv4Mopk0XGBwq6IMRBXHTP0FMTRekCFJyeEi6pqU+GnFMYl3aoyDF+jg3bY4ci6hoPzTY=
  - secure: bg8D9/i8X7xCs2q+sWwlPYPUeDZdhc6n7BzBPbkvFTMlPpeoku8j+wzhakNoA+P/CJeK7p/aJUeo7r5WXOAp857csv2XD1Z+W4GayW6EFsuBeQgaWN1pMsz0+s+o3tk5eD/qonLBZiHlwZwbsrszit69qdXE/CisRxPhg0GyP3uIIGqrY6avFgsCyHYbr3oIilNEKFTYWo0bj8d4yfkMOsKHTgzHysDycNgPbxA4wI4p+0ZKtvrZm/5Psa3h99VirIyESMnx3AyIGBRxFTjjfDQxnaoH8GHCTOaZG6FjfhMy2eMq3fcAYYQhPPss6BIy0tcHvBrVO0ENHBERg8rmFX2nkMvb2XILL+Ipiau46B34ucX9stZTKCP2xcc/ohLwgkCTuhZq562zBq8ttkWpAQDnQuZyodz0Y22TedgjrQWGURXbNTs1tMS8uwZqXpFxBq/zJWh+JcGO5BClgW74PziX71Z1Q+nLJKi8e6FayFr+q+UVqarB3C6I8kvSCEWmreAVPJmpJY+/TouO8xh53syJkhJIQM+OnuaejUU0D04uhq5XxXu0sahWt8i/Jv7clp86oVFArFAPuez01CrP8m5o+q+eQHAzQy0zr0Q6TdQcHPtnD7PgHeA8ioypVko5EkhomFf+EEJP3NeRsSBJxSkNhOfULqiht9Z1q9ltHIc=
before_script:
- npm install -g bower gulp web-component-tester
- npm install
- bower install
- gulp
- gulp build
script:
- "./travis-runner.sh"
